version: "3.8"
services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    # depends_on:
    #   - postgres
    environment:
      DBURL: ep-polished-snowflake-a2kuegdr.eu-central-1.pg.koyeb.app/koyebdb
      DBNAME: library-app-db
      DBUSERNAME: koyeb-adm
      DBPASSWORD: npg_W3dUmjznO4tI

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: library-app-db
  #     POSTGRES_USER: koyeb-adm
  #     POSTGRES_PASSWORD: npg_W3dUmjznO4tI
  #   ports:
  #     - "5432:5432"
